# Generated by Django 5.2.8 on 2025-11-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Enter product name', max_length=30)),
                ('product_id', models.IntegerField(help_text='Enter product id')),
                ('product_descr', models.CharField(help_text='Write description', max_length=50)),
                ('product_price', models.IntegerField(help_text='Enter price')),
            ],
        ),
    ]
